export const USER_LOAN_REQUEST = "USER_LOAN_REQUEST";
export const USER_LOAN_FAIL = "USER_LOAN_FAIL";
export const USER_LOAN_SUCCESS = "USER_LOAN_SUCCESS";
export const USER_LOAN_RESET = "USER_LOAN_RESET";
